name: Release dev-quality-level-N versions

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Set up GIT in bin
      run: |
        cd bin
        git init
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
        git fetch origin

    - name: Generate no unsupported versions release
      run: |
        cd bin
        git checkout no-no-unsupported-versions -f || git checkout -b no-no-unsupported-versions 7c16065
        ./ddqg-generate-no-no-unsupported-versions
        composer validate
        # If this is a newly created branch then composer.json is not being tracked.
        git add composer.json
        if [[ `git status --porcelain --untracked-files=no` ]]; then
          git commit -a -m "Updated composer.json"
          git push -f -u origin no-no-unsupported-versions
        fi

    - name: Generate no insecure versions release
      run: |
        cd bin
        git checkout no-no-insecure-versions -f || git checkout -b no-no-insecure-versions 7c16065
        ./ddqg-generate-no-no-insecure-versions
        composer validate
        # If this is a newly created branch then composer.json is not being tracked.
        git add composer.json
        if [[ `git status --porcelain --untracked-files=no` ]]; then
          git commit -a -m "Updated composer.json"
          git push -f -u origin no-no-insecure-versions
        fi
